### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by elliotwave** [khancyr/ardupilot_gazebo#12]
Hi, I am using gazebo 7 as it's the version that is supported by ROS kinetic. I had a problem on "cmake .." step. It's written that I need 7.X.Y version while I already had 7.14.0 version. Is there any way to fix it? 

![error](https://user-images.githubusercontent.com/47345317/52255842-cc16b300-2946-11e9-99bb-bad951937682.png)

**Comment by khancyr** [comment]
Hello,

Thanks for report, I will correct that briefly

**Comment by johnbdk** [comment]
Hello,

Same error here.

**Comment by khancyr** [comment]
@johnbdk Hello, 
I have fix the cmake rules ! 
It should be good now

**Comment by johnbdk** [comment]
Great, it was simple. I just mentioned this for feedback purposes.
By the way, excellent work.

**Comment by khancyr** [comment]
Thanks for the feedback.

I am closing this now
