### ISSUE TITLE
Arducopter crashes regularly

### ISSUE THREAD

**Issue by rishab26201** [khancyr/ardupilot_gazebo#18]
Hey,
So I arm and take off the drone. But it goes above the given setpoint and crashes. Even if it doesn't it keeps oscillating (+/-2 m) and is very unstable. Is there any way to correct this. Also for thrust input of 0.5 from setpoint_raw/attitude the drone moves sideways even though I dont give roll or yaw. Is there any way to correct this

**Comment by darshanz** [comment]
were you able to fix this, I am having same problem.

**Comment by rishab26201** [comment]
Yes I replaced the URDF with one from Px4. Try this.
[https://github.com/rishab26201/SDRE_Landing/tree/master/iris_with_standoffs](url)

**Comment by darshanz** [comment]
Thanks, I will try that tonight.
