### ISSUE TITLE
Gazebo 11 support coming?

### ISSUE THREAD

**Issue by linuxsocke** [khancyr/ardupilot_gazebo#31]
Hi, 
I want to use gazebo-ros and Ubuntu 20.04. Is there a support for gazebo 11 coming?

**Comment by acxz** [comment]
Hi @linuxsocke 
ardupilot_gazebo does work with Gazebo 11. I ran into #27 but I was able to fix that error with #28 
While we wait for @khancyr to merge that PR in, feel free to use [my fork](https://github.com/acxz/ardupilot_gazebo)

I am using it on Pop OS 20
