### ISSUE TITLE
Unable to find uri[model://iris_with_ardupilot]

### ISSUE THREAD

**Issue by linuxsocke** [khancyr/ardupilot_gazebo#33]
Hi, 

After running gazebo --verbose worlds/iris_arducopter_runway.world
it tells:
Gazebo multi-robot simulator, version 9.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
Gazebo multi-robot simulator, version 9.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.122.1
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.122.1
[Wrn] [ModelDatabase.cc:340] Getting models from[http://models.gazebosim.org/]. This may take a few seconds.
[Wrn] [FuelModelDatabase.cc:248] URI not supported by Fuel [model://iris_with_ardupilot]
[Wrn] [SystemPaths.cc:464] File or path does not exist [""] [model://iris_with_ardupilot]
Error Code 11 Msg: Unable to find uri[model://iris_with_ardupilot]
[Wrn] [Publisher.cc:135] Queue limit reached for topic /gazebo/default/physics/contacts, deleting message. This warning is printed only once.

I have the folder /usr/share/gazebo-9/models/iris_with_ardupilot with the .config and .sdf file in it ..

**Comment by acxz** [comment]
@linuxsocke after installing gazebo you can source the gazebo setup.{ba,z}sh file to get access to the models. i.e. `source /usr/share/gazebo/setup.sh`

You can add something like this to your {ba,z}shrc to ensure they get loaded at every shell instantiation:
```
stat /usr/share/gazebo/setup.sh &> /dev/null
if [ $/ -eq 0 ]; then
    source /usr/share/gazebo/setup.sh
fi
```

**Comment by linuxsocke** [comment]
Sorry this was not mentioned in the [steps](https://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html#plugin-installation) I followed.

**Comment by acxz** [comment]
Ah, its best to look at the documentation closest to the source as well ;)
Did sourcing this resolve your issue? If so you can go ahead and close this issue.

**Comment by linuxsocke** [comment]
Yes thanks

**Comment by Gunz-devs** [comment]
http://models.gazebosim.org/ - model deprecated from site. can you link the model file here
