### ISSUE TITLE
Errors with new API

### ISSUE THREAD

**Issue by pem811** [khancyr/ardupilot_gazebo#9]
Will not work with Gazebo9 unless certain methods fixed, see http://osrf-distributions.s3.amazonaws.com/gazebo/api/dev/classgazebo_1_1rendering_1_1Visual.html 

Ex. gazebo::rendering::Name() instead of GetName().

**Comment by khancyr** [comment]
hello,
yes I know I didn't finish the port for gazebo 9.
Did you try on master branch or dev8 ?

**Comment by pem811** [comment]
Master. I did go through and fix all the problems I saw and it does seem to be working for me.

**Comment by umer936** [comment]
There's a PR from this fork that you could cherry pick to get the port for gazebo9: https://github.com/SwiftGust/ardupilot_gazebo/tree/gazebo9

**Comment by khancyr** [comment]
@umer936 I correct the support for gazebo9 already. Thanks
